# Відключаємо цей workflow, оскільки ми використовуємо вбудований GitHub Pages
name: Disabled

on:
  # Вимкнено відстеження всіх подій
  workflow_dispatch:

jobs:
  nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow is disabled" 